In [1]:
#Polynomial Regression Codes with performance metrics checks

In [2]:
#Import all the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#import the dataset
dataset = pd.read_csv("Data.csv")

In [4]:
#Split the dataset into train and test
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [5]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [6]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [7]:
#Split the dataset into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [8]:
#Train the Polynomial Regression Features
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree=4)
regressor=LinearRegression()
X_poly = poly_reg.fit_transform(X_train)
regressor.fit(X_poly,y_train)

LinearRegression()

In [9]:
#Predicting the test set result
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.67 463.28]]


In [10]:
#Evaaluating the model performance
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9458193001159928